name: Bump Version
on:
  # mainから呼び出す
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  BumpVersion:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    outputs:
      release_type: ${{ steps.tag_version.outputs.release_type }}
      new_tag: ${{ steps.tag_version.outputs.new_tag }}
      changelog: ${{ steps.tag_version.outputs.changelog }}
    steps:
      - uses: actions/checkout@v3

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.token }}
          default_bump : false
          dry_run: true  # tagはRelease作成時つける

  CreateRelease:
    needs: BumpVersion
    if: ${{ needs.BumpVersion.outputs.release_type != false }}
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - name: Set version
        run: sed -i -e 's/v[0-9]\+\.[0-9]\+\.[0-9]\+/${{ needs.BumpVersion.outputs.new_tag }}/' library.properties library.json

      - name: Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push version
        env:
          branch: "release/${{ needs.BumpVersion.outputs.new_tag }}"
        run: |
          git switch -c ${{ env.branch }}
          git add .
          git commit -m "Bump version: ${{ needs.BumpVersion.outputs.new_tag }}"
          git tag -a ${{ needs.BumpVersion.outputs.new_tag }} -m "Bump version: ${{ needs.BumpVersion.outputs.new_tag }}"
          git push origin ${{ needs.BumpVersion.outputs.new_tag }}

      - run: echo GITHUB_REF_NAME:${GITHUB_REF_NAME}
      - run: echo GITHUB_ACTOR:${GITHUB_ACTOR}
      - run: echo env.branch:${{env.branch}}

      - name: Create and merge Pull Request
        env:
          GH_TOKEN: ${{ secrets.token }}
          branch: "release/${{ needs.BumpVersion.outputs.new_tag }}"
        run: |
          gh pr create --base ${GITHUB_REF_NAME} --head ${{env.branch}} --assignee ${GITHUB_ACTOR} \
             --title "Bump version: ${{ needs.BumpVersion.outputs.new_tag }}" --body 'TODO URL'
          gh pr merge ${{env.branch}} --merge --delete-branch

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.BumpVersion.outputs.new_tag }}
          body: ${{ needs.BumpVersion.outputs.changelog }}
